# Generated by Django 5.1.4 on 2024-12-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2024/04/17/18/40/ai-generated-8702726_1280.jpg', max_length=2000),
            preserve_default=False,
        ),
    ]
